name: zartek_test
description: zartek Test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  dio: ^4.0.6
  google_sign_in: ^5.3.0
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  shared_preferences: ^2.0.13
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/auth/
